<!-- question-type: inclass -->
### Exercise 5: Improving the Price-Distance Relationship Plot

**(a).** Together with your peers, propose two changes you want to make to the plot in Exercise 3. Discuss the rationale behind each change and how it might improve the visualization.

**(b).** Work with your tutor to create an agreed upon list of changes to make to the plot. What steps do you need to take to make these improvements?

**(c).** Implement the changes suggested in the R.

<!-- BEGIN PROFILE:r-teaching-guide -->
::: {.content-visible when-profile="r-teaching-guide"}

::: {.teaching-block}

::: {.teaching-block-header}
Teaching Note
:::

::: {.teaching-block-body}

🎯 **Learning Objective** 
Students should:

- Evaluate and improve a basic scatter plot via aesthetic improvements

✅   **Core Concepts to Highlight**

- aesthetic improvements can improve readabiity of the plot as much as analytical ones

💬 **Suggested In-Class Prompts** (if needed)


📌 **Common Misunderstandings**

- Confusing aesthetic improvements (e.g., color, centered title) with analytical ones — both matter, but for different reasons
:::

:::

:::
<!-- END PROFILE:r-teaching-guide -->

<!-- BEGIN PROFILE:r-solutions -->
::: {.content-visible when-profile="r-solutions" when-profile="r-teaching-guide"}

::: {.solution-block}

::: {.solution-block-header}
Solution
:::

::: {.solution-block-body}

**(a) and (b)**

**Analytical structure mostly unchanged**

* same variables on the axes
* same scatterplot
* same transparency level
* same linear fitted line

Non exhaustive list of potential changes focussed around presentation improvements

* clearer color contrast between points and line
* easier-to-read price axis
* more polished theme and title formatting

**(c)**

```{r}
# Improved scatterplot: price vs. distance
scttr <-
    ggplot(housing,
           aes(x = distance, y = price)
           ) +
     # Scatter plot with reduced alpha to handle overplotting
    geom_point(alpha = 0.05, color = "grey") +
    geom_smooth(
        method = "lm",
        se = FALSE,
        color = "coral",
        linewidth = 1
    ) +
    # Format y-axis as dollars
    scale_y_continuous(labels = scales::dollar) +
    # Add labels and center the title
    labs(
        x = "Distance to CBD (km)",
        y = "Price",
        title = "Dwelling Price vs. Distance"
    ) +
    theme_bw() +
    theme(
        plot.title = element_text(hjust = 0.5)
    ) 

scttr
```


:::

:::

:::
<!-- END PROFILE:r-solutions -->